name: Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Main
        run: |
          # Add your deployment commands here
          # For example, if you're deploying a Node.js app:
          # npm install
          # npm run build
          # Your deployment command

      - name: Deploy to Digital Ocean Main Server
        run: |
            ssh ${{ secrets.SERVER_USERNAME }}@${{secrets.SERVER_IP}} "cd /digital-ocean-cicd && git pull origin main && pm2 restart src/app.js"

