name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: digital-ocean-cicd

      - name: Update repository or clone if not exists
        run: |
          if [ -d "digital-ocean-cicd/.git" ]; then
            cd digital-ocean-cicd
            git pull origin main
          else
            git clone https://github.com/gaiyadev/digital-ocean-cicd.git
            cd digital-ocean-cicd
          fi
        working-directory: digital-ocean-cicd

      - name: Install dependencies and restart application
        run: |
          npm install
          pm2 src/app.js
        working-directory: digital-ocean-cicd
