name: Digital Ocean Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Debug SSH Key
      run: |
        echo "$SSH_PRIVATE_KEY"

    - name: Deploying to server
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key
        chmod 600 /tmp/private_key
        scp -o StrictHostKeyChecking=no -i /tmp/private_key -r . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:~/digital-ocean-cicd
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'cd ~/digital-ocean-cicd && git pull origin main && npm install && pm2 restart src/app.js'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
