name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          port: 22
          script: |
                    git clone https://github.com/gaiyadev/digital-ocean-cicd.git
                    cd digital-ocean-cicd
                    npm install
                    pm2 restart ./src/app.js