name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # - name: Build
      #   run: npm run build

      - name: Deploy
        run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << EOF
            cd /path/to/your/application
            git pull origin main
            npm install
            npm run build
            pm2 restart app
          EOF