name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SERVER_IP}} 
          key: ${{secrets.SSH_PRIVATE_KEY}} 
          username: ${{ secrets.SERVER_USERNAME }} 
     
          script: |
            mkdir digital-ocean-cicd 
            cd digital-ocean-cicd 
            git clone https://github.com/gaiyadev/digital-ocean-cicd.git
            npm insall
            pm2 restart digital-ocean-cicd/digital-ocean-cicd/src/app.js
            echo 'Deployment successful to digital ocean' 