name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: digital-ocean-cicd

      - name: Install dependencies
        run: |
          cd digital-ocean-cicd
          npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: digital-ocean-cicd

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd home/runner/work/digital-ocean-cicd/digital-ocean-cicd/digital-ocean-cicd
            git pull origin main
            npm install
            pm2 restart src/app.js
