name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}  # IP address of your DigitalOcean droplet
          username: ${{ secrets.SERVER_USERNAME }}  # SSH username for your droplet
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key used for authentication
          port: 22  # SSH port (default is 22)
          script: |
            cd digital-ocean-cicd
            git pull origin main
            npm install
            pm2 restart src/app.js
