name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir digital-ocean-cicd 
            cd digital-ocean-cicd 
            git clone https://github.com/gaiyadev/digital-ocean-cicd.git
            cd digital-ocean-cicd 
            pm2 restart src/app.js
            echo 'Deployment successful to digital ocean' 