name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and Deploy to DigitalOcean
        run: |
         pwd
         ls -R
          # cd digital-ocean-cicd 
          # git pull origin main        
          # cd src  
          # npm install
          # pm2 restart app.js
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
