name: Digital Ocean Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and Deploy to DigitalOcean
        run: |
          cd /home/runner/work/digital-ocean-cicd/digital-ocean-cicd
          npm install
          npx pm2 restart /home/runner/work/digital-ocean-cicd/digital-ocean-cicd/src/app.js
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
