name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Main
      if: github.ref == 'refs/heads/main'
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{secrets.SERVER_IP}} "cd /path/to/main/app && git pull origin main && npm install && pm2 restart app.js"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Dev
      if: github.ref == 'refs/heads/dev'
      run: |
        ssh user@dev-droplet-ip-address "cd /path/to/dev/app && git pull origin dev && npm install && pm2 restart app.js"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
